<!DOCTYPE html>
<html>
<head>
    <title>Delivery Note PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
        }
        .content {
            width: 100%;
            margin: 0;
            padding: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        td {
            padding: 4px;
           /*  border: 1px solid black; */ /* Add border around each cell */
        }
        .section-title {
            font-weight: bold;
            margin-bottom: 12px;
        }
        .lot-number {
            display: block;
            margin-top: 5px;
        }
    </style>
</head>
<body>

    <div class="content">
        <table style="margin-left: -1.2cm;">
            <!-- Delivery Note Information -->
            <tr>
                <td style="width: 30%;"></td>
                <td style="width: 65%;"> {{ $deliveryNote->customer_po_number }}</td>
                <td style="width: 30%;"> {{ \Carbon\Carbon::parse($deliveryNote->date)->format('d-m-Y') }}</td>
                <td style="width: 30%;"> {{ now()->format('H:i:s') }}</td>
            </tr> <br> <br>
            <tr>
                <td style="width: 30%;"></td>
                <td> {{ $deliveryNote->driver_license }}   <br>{{ $deliveryNote->destination }}</td>
                <td>{{ $deliveryNote->transportation }}</td>
                <td>{{ $deliveryNote->plat_no }}</td>
                <td></td>
            </tr>
            <br><br>
            <tr>
                <td style="width: 30%;"></td>
                <td> </td>
                <td></td>
                <td></td>
            </tr>
        </table>

        <br/> <br><br>

        <!-- Delivery Note Details -->
        @foreach ($deliveryNoteDetails as $index => $detail)
        <table style="margin-left: -1.35cm;">
                <tr>
                    <td style="width: 1cm;">{{ str_pad($index + 1, 3, '0', STR_PAD_LEFT) }}</td>
                    <td style="width: 4cm;"> {{ $detail->part_no }}</td>
                    <td style="width: 5cm;"> {{ $detail->part_name }}</td>
                    <td style="width: 5cm;">@if($detail->group_no) {{ $detail->group_no }} @endif</td>
                    <td style="width: 3cm;"> {{ $detail->qty }}</td>
                    <td style="width: 5cm;"> {{ $detail->remarks }}</td>
                </tr>
            </table>
        @endforeach

        <br/><br/><br>
        <p>Generated by System</p>
    </div>
</body>
</html>
