<!DOCTYPE html>
<html>
<head>
    <title>Delivery Note PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
        }
        .content {
            width: 100%;
            margin: 0;
            padding: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        td {
            padding: 4px;
        }
        .section-title {
            font-weight: bold;
            margin-bottom: 12px;
        }
        .lot-number {
            display: block;
            margin-top: 5px;
        }
    </style>
</head>
<br><br><br>
<body>

    <div class="content">
        <table>
            <!-- Delivery Note Information -->
            <tr>
                <td style="width: 30%;"></td>
                <td style="width: 65%;"> {{ $deliveryNote->customer_po_number }}</td>
                <td style="width: 30%;"> {{ \Carbon\Carbon::parse($deliveryNote->date)->format('d-m-Y') }}</td>
                <td style="width: 30%;"> {{ now()->format('H:i:s') }}</td>
            </tr> <br> <br>
            <tr>
                <td style="width: 30%;"></td>
                <td> {{ $deliveryNote->driver_license }}   <br>{{ $deliveryNote->destination }}</td>
                <td>{{ $deliveryNote->transportation }}</td>
                <td>{{ $deliveryNote->plat_no }}</td>
                <td></td>
            </tr>
            <br><br>
            <tr>
                <td style="width: 30%;"></td>
                <td> </td>
                <td></td>
                <td></td>
            </tr>
        </table>

        <br/> <br><br>

        <!-- Delivery Note Details -->
        @foreach ($deliveryNoteDetails as $index => $detail)
            <table>
                <tr>
                    <td style="width: 3%;">{{ str_pad($index + 1, 3, '0', STR_PAD_LEFT) }}</td>
                    <td style="width: 20%;"> {{ $detail->part_no }}</td>
                    <td style="width: 30%;"> {{ $detail->part_name }}</td>
                    <td style="width: 20%;">@if($detail->group_no) {{ $detail->group_no }} @endif</td>
                    <td style="width: 10%;"> {{ $detail->qty }}</td>
                    <td style="width: 10%;"> {{ $detail->remarks }}</td>
                </tr>
            </table>
        @endforeach

        <br/><br/>
        <p>Generated by System</p>
    </div>
</body>
</html>
